main: "site.pegasis.mc.team_speedrun.MCTeamSpeedRun"
version: "1.5"
name: "Pega-Team-Speedrun"
author: "Pegasis"
api-version: "1.16"
depend: [LuckPerms]

commands:
  start-speedrun:
    description: Start speedrun.
    permission: team_speedrun.start
  end-speedrun:
    description: End speedrun.
    permission: team_speedrun.end
  resume-speedrun:
    description: Resume speedrun.
    permission: team_speedrun.resume
  reset-player:
    description: Resume speedrun.
    permission: team_speedrun.reset_player
  get-compass:
    description: Give a compass to the caller.
    permission: team_speedrun.get_compass
  quit:
    description: Quit the speedrun.
    permission: team_speedrun.quit

permissions:
  team_speedrun.*:
    description: Gives access to start or end the speedrun.
    default: op
  team_speedrun.get_compass:
    description: Gives access to get compass.
    default: true
  team_speedrun.quit:
    description: allow players to quit themselves.
    default: true
